# Generated by Django 4.2.5 on 2023-09-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=20, null=True)),
                ('organization', models.CharField(max_length=20, null=True)),
                ('monthly_income', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Iitial_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('height', models.IntegerField(null=True)),
                ('body_color', models.CharField(max_length=20, null=True)),
                ('present_adress', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Family_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.CharField(max_length=100, null=True)),
                ('father_profession', models.CharField(max_length=20, null=True)),
                ('mother_profession', models.CharField(max_length=20, null=True)),
                ('number_of_bro', models.CharField(max_length=20, null=True)),
                ('number_of_sister', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Educational_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_year', models.IntegerField(null=True)),
                ('ssc_result', models.CharField(max_length=20, null=True)),
                ('hsc_year', models.IntegerField(null=True)),
                ('hsc_result', models.CharField(max_length=20, null=True)),
                ('university', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('bachelor_completed_year', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Desired_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_person_profession', models.CharField(max_length=80, null=True)),
                ('desired_person_height', models.CharField(max_length=20, null=True)),
                ('desired_person_age', models.CharField(max_length=20, null=True)),
                ('desired_person_education', models.CharField(max_length=50, null=True)),
                ('desired_person_qualities', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
