# Generated by Django 4.2.6 on 2024-01-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='iitial_info',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
